### PR TITLE
Use ReactJS framework

### LINKED ISSUE #5: Investigate frameworks and make recommendations

### PR DESCRIPTION
**Pull request by Beck-berry**
### Tasks
I created a new React app based on the previous files and processes. I came up with a list of things, I should have copied from the old version. Please let me know, if there is any other requirements I forgot about.

- [x] display the correct map
- [x] display the search field at the top
- [x] have autocomplete on the search field
- [x] jump (set the center of the map) to the selected location
- [x] use the NavigationControl of the map (bottom left corner): zoom
- [x] use the `bikely` layer
- [x] parse the opening URL and show the requested route if any
- [x] on map clicks: show the start and destination markers, update the URL and plan a route
- [x] reset route
- [x] show help popup
- [x] give example route (in help popup)
- [x] layer switch (top right corner)
- [x] show legend
- [x] show map coordinates in the URL
- [x] show bikely popups
- [x] recompute route on marker drag

Also added an AttributionControl (bottom right corner) as #4 requested. 

Also added a GeolocateControl to the top left corner (as #2 mentioned) so you can see and test whether that's what we want here.

### Versions
- npm 9.4.0
- node 14.18.3

### Screenshots
Képernyőkép_2023-02-03_20-48-53
Képernyőkép_2023-02-03_20-48-31
Képernyőkép_2023-02-03_20-49-39
Képernyőkép_2023-02-03_21-26-14

Closes #5

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
I just tried to run `npm start` and got the following error:

```
Failed to compile.

Module not found: Error: Can't resolve '../styles/map.css' in '/home/lenni/dev/norway/cycling-norway/src/components'
ERROR in ./src/components/Map.js 6:0-27
Module not found: Error: Can't resolve '../styles/map.css' in '/home/lenni/dev/norway/cycling-norway/src/components'

ERROR in ./src/index.js 8:0-48
Module not found: Error: Can't resolve './reportWebVitals' in '/home/lenni/dev/norway/cycling-norway/src'

webpack compiled with 2 errors
```

Do you know what that is?

Regarding the legend: it should show up exactly as in the current deployment at https://leonard.io/cycling-norway/

In your screenshot I don't see any icons or lines from the map. Did you wrap the original library or re-implement it?

**Comment by Beck-berry** [comment]
Sorry, I probably missed adding those files to the commit... Now it should be working!

By icons, did you mean the bike parking places and so? I have those. I used the Maplibre library and the same map.

Képernyőkép_2023-02-06_08-21-54

**Comment by leonardehrenfried** [comment]
Ok, now it's working.

However, the legend ("Tegnvorklaring") doesn't show the items on the map.

## Before

Screenshot from 2023-02-06 09-27-04

## After

Screenshot from 2023-02-06 09-26-46

It should automatically update with what is visible on the map.

**Comment by Beck-berry** [comment]
Képernyőkép_2023-02-10_21-42-59

**Comment by Beck-berry** [comment]
We could also use the LegendControl to toggle the layers:

Képernyőkép_2023-02-10_21-56-20

**Comment by leonardehrenfried** [comment]
The screenshot looks great but I cannot run the app. I get the following error:

```
./node_modules/react-map-gl/dist/esm/components/map.js
Module not found: Can't resolve 'mapbox-gl' in '/home/lenni/dev/norway/cycling-norway/node_modules/react-map-gl/dist/esm/components'
```

**Comment by Beck-berry** [comment]
Hm, weird. I deleted the `node_modules` folder and the `package-lock.json` file, then reinstalled with `npm i` and then could start the application. What else can I try to reproduce your error?
Note, that after the installation, there should be a `mapbox-gl` directory in the `node_modules`, as it is a dependency of the `react-map-gl` library. Do you use the same version of npm as I?

**Comment by leonardehrenfried** [comment]
I had to do this https://github.com/buskerudbyen/cycling-norway/pull/6/commits/a8cbc82cfb74793f52b477b95d8dc77b5b54f7ef to make it work on my computer. :man_shrugging: 

This looks quite good.

Is there a way to convert this app into fully static HTML and CSS?

**Comment by leonardehrenfried** [comment]
Also, can you make the lines for the cycling networks a bit thicker in the legend?

Screenshot from 2023-02-13 21-01-03

**Comment by Beck-berry** [comment]
> Is there a way to convert this app into fully static HTML and CSS?

Yes, run `npm run build` and I think the `build` folder is what you're looking for.

**Comment by leonardehrenfried** [comment]
Ok, the lines look really nice now, thanks!

If you could re-add the coordinates in the URL I think we can merge this. In regular maplibre the property is called `options.hash`: https://maplibre.org/maplibre-gl-js-docs/api/map/

**Comment by leonardehrenfried** [comment]
Oh hang on, there is one thing that I would like you to take a look at. When I build production bundle with `npm run build` and run I get a white map and a strange error:

Screenshot from 2023-02-14 22-08-51

Could you please take a look at this?

**Comment by Beck-berry** [comment]
It is a known problem in the mapbox-gl v2 ([react-map-gl#1266](https://github.com/visgl/react-map-gl/issues/1266)), they came up with a few official ways to solve it: https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling

I tried the first one, updated the browserlist in `package.json`, now it works in production. Are you ok with that solution?

**Comment by leonardehrenfried** [comment]
That's fine.

**Pull request merged**
