### PR TITLE
Improve snow plow visualization

### LINKED ISSUE #14: Add legend/explanation for snow plowing colours
Please check if it's possible to add items to the legend about what the snow plowing colours mean.

- green: plowed less than 3 hours ago
- red: plowed more than 3 hours ago

### LINKED ISSUE #20: Improve demo/test for snow plowing information
Right now you can activate the snow plowing simulation by adding `?simulateSnowPlows` to the URL, like this: https://leonard.io/cycling-norway/?simulateSnowPlows#14/59.739/10.1878

This demo mode however only takes the real data and applies styling to existing data.

Right now however, we don't have any data so the simulation doesn't show anything. Therefore we want to add additional demo data.

### Acceptance criteria

- Take some demo data from the existing (static) data
- Add it as a static resource to this repo
- When running in simlulation mode download the demo data instead of taking realtime data

### PR DESCRIPTION
**Pull request by Beck-berry**
Changes: 
* added static sample / demo data
* kept the random coloring in demo / test mode
* snow plow *demo* data is collected only when `?simulateSnowPlows` is in the query
* snow plow *real-time* data is collected only when `?showSnowPlows` is in the query
* "old" routes are coloured yellow/orange
* updated popup text

Képernyőkép_2023-03-15_16-54-55

Closes #14 
Closes #20

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
image

I tried testing it but I cannot see any simulated snow plowing tracks. Am I using the correct URL?

**Comment by leonardehrenfried** [comment]
I just tried it and it works but we should simplify the logic:

- realtime snow plow data should be shown by default
- use simulated data if `simulateSnowPlows` is in the URL
- remove `showSnowPlows` param handling

**Review by leonardehrenfried — CHANGES_REQUESTED** [review]
I just tried it and it works but we should simplify the logic:

- realtime snow plow data should be shown by default
- use simulated data if simulateSnowPlows is in the URL
- remove showSnowPlows param handling

**Comment by Beck-berry** [comment]
@tsobuskerudbyen asked for a switch for the snow plow visualization in the [connected issue](https://github.com/buskerudbyen/cycling-norway/issues/14#issuecomment-1465773447), this is why I introduced the `showSnowPlows` param. Do you have another suggestion for that?

**Comment by leonardehrenfried** [comment]
Okay, can we do the the following

- the default is no snow plows
- one param for real-time snow plows
- one param for simulated ones
- if both are set the the realtime takes precedence

**Comment by Beck-berry** [comment]
Done :tada:

**Pull request merged**
