### PR TITLE
Add elevation info

### LINKED ISSUE #38: Add elevation info
Extend the routing info created in #3 with elevation.

@leonardehrenfried [wrote](https://github.com/buskerudbyen/cycling-norway/issues/3#issuecomment-1508697128):
> Actually I just checked: the elevation information is not available in the API even though Entur's OTP instance has it.
I will have to speak to their developers if they are interested in adding it.

- [ ] get elevation info from API
- [ ] find / create an icon
- [ ] add icon and elevation data to the side panel, next to the distance

### PR DESCRIPTION
**Pull request by Beck-berry**
I added the elevation info, it is displayed on the side panel after a search was made. It can be a negative number if the elevation of the start is bigger than at the end of the route.

<details>
<summary>Screenshots</summary>

Képernyőkép_2023-07-06_21-04-47

Képernyőkép_2023-07-06_21-05-18

Képernyőkép_2023-07-06_21-16-23

</details>

Closes #38

### CODE REVIEW

**Comment by Beck-berry** [comment]
@tsobuskerudbyen What do you think about the icon?

**Comment by leonardehrenfried** [comment]
Sorry for the very late reply, but I think @tsobuskerudbyen was more looking for an elevation profile. Something like this:

image

Am I right @tsobuskerudbyen ?

**Comment by tsobuskerudbyen** [comment]
Yes, you are right @leonardehrenfried. (Shortly in from summer holidays here.)

**Comment by Beck-berry** [comment]
Then I'll close this PR and move #38 to the ToDo column. I'll have to rethink my approach.

**Comment by Beck-berry** [comment]
@leonardehrenfried Please check this, we discussed that this can be a base for #68. After that I'll add the graphical solution.

**Pull request merged**
